global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  insecure: true

providers:
  docker: {}
  file:
    directory: /config
    watch: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
  https:
    address: ":443"
  tcptls:
    address: ":9090"

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    # manualRouting: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5
    # entryPoint: metrics