global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  insecure: true
providers:
  docker: {}
  file:
    directory: /certs
    watch: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
  https:
    address: ":443"