global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

# accesslog:

api:
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: /config
    watch: true
  # redis:
  #   rootKey: "traefik"
  #   endpoints:
  #     - localhost:6379
  #     # within the same pod, container share the network namespace (ip, ports etc)

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
  https:
    address: ":443"
  tcptls:
    address: ":9090"

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    # manualRouting: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5
    # entryPoint: metrics
