tls:
  certificates:
    -
      certFile: /certs/fullchain.pem
      keyFile:  /certs/privkey.pem    
  stores:
    default:
      defaultCertificate:
        certFile: /certs/fullchain.pem
        keyFile:  /certs/privkey.pem
  # options:
  #   foo:
  #     minVersion: VersionTLS12
  #     cipherSuites:
  #       - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  #       - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
  #       - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
  #       - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  #       - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256